import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_623.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();WORKS=['001','002','003','004','005'];canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for work in WORKS:
  s=canon[('0067',work)];row={f:'' for f in FIELDS};row.update(tlg_author_id='0067',tlg_work_id=work,author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Agatharchides Canon notice; local First1K Müller TEI; Giannini/FGrH and duplicate boundaries checked.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
  c=[r for r in matches if r['tlg_author_id']=='0067' and r['tlg_work_id']==work and r['corpus']=='First1KGreek'];v=[r for r in checks if r['tlg_author_id']=='0067' and r['tlg_work_id']==work and r['corpus']=='First1KGreek']
  if work=='001' and len(c)==len(v)==1 and v[0]['automated_check']=='AUTOMATED_TEI_CHECK_PASSED': row.update(open_text_result='Complete Greek excerpt corpus verified in the exact K. Müller 1855 edition cited by the Canon.',open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_EXACT_EDITION',next_action='Prepare exact licensed TEI for ingestion.',notes=f"Exact URN {c[0]['cts_urn']}; {v[0]['greek_characters']} Greek characters; no OCR/images used.")
  else: row.update(open_text_result='No complete licensed Greek transcription matching this exact separate fragment/testimony edition was verified.',confidence='medium',proposed_status='NO_COMPLETE_OPEN_TEXT',next_action='Map each item to ancient hosts before acquisition.',notes='Müller excerpts are not extended to Giannini or FGrH aggregates; partial duplicate 0067.005→004 preserved; no OCR/images used.')
  w.writerow(row)
