import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_637.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();TARGETS=[('0096','017'),('0096','195'),('0098','001'),('0099','001'),('0099','002')];canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for key in TARGETS:
  s=canon[key];c=[r for r in matches if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1]];v=[r for r in checks if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['automated_check']=='AUTOMATED_TEI_CHECK_PASSED'];row={f:'' for f in FIELDS};row.update(tlg_author_id=key[0],tlg_work_id=key[1],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local licensed TEI registries and extraction boundary checked.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
  if key in {('0098','001'),('0099','001')} and c and v: row.update(open_text_result='Complete Greek TEI verified in the exact historical edition cited by the Canon.',open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_EXACT_EDITION',next_action='Prepare exact licensed TEI.',notes=f"Exact URN {c[0]['cts_urn']}; {v[0]['greek_characters']} Greek characters; no OCR/images used.")
  elif key==('0096','195'): row.update(open_text_result='Malformed continuation row containing only a trailing number list; no autonomous work or text is inferred.',confidence='high',proposed_status='INCOMPLETE_CONTINUATION_NOTICE_NO_EXACT_TEXT',next_action='Repair linkage to the preceding Aesop notice from the original Canon typography.',notes='No invented title, genre, edition or count.')
  elif key==('0099','002'): row.update(open_text_result='No complete licensed transcription of the separate FGrH testimony was verified.',confidence='medium',proposed_status='NO_COMPLETE_OPEN_TEXT',next_action='Map the testimony to its ancient host.',notes='The full Strabo text is not substituted for an unidentified testimony.')
  else: row.update(open_text_result='No exact licensed Greek transcription of this proverb subset was verified.',confidence='medium',proposed_status='NO_EXACT_OPEN_TEXT',next_action='Map against open paroemiographic collections item by item.',notes='No automatic inclusion in Aesop collection inferred.')
  w.writerow(row)
