import csv
O='data/research_batches/detailed_verified_3001_batch_546.csv';F='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split()
D={('4533','001'):('MPG 140 cols.417–468','9,769','The liturgical commentary and embedded locus are preserved.'),('4534','001'):('MPG 140 cols.388–413','5,161','The epistolary sermon remains distinct.'),('4534','002'):('Karpozilos 1974 pp.238–248, even pages; Oxon.Barocc.131','2,022','The even-page restriction and Germanus II cross-reference are preserved.'),('4535','001'):('Lampros 1878 pp.268–273','','The Canon supplies no count; none is invented.'),('4538','001'):('Treu 1899 pp.1–14','', 'BHG 947 is preserved; the exact 1899 volume has a free Google Books/HathiTrust image candidate, not yet Greek-sampled.')}
C={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))}
with open(O,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=F,lineterminator='\n');w.writeheader()
 for k,(l,c,n) in D.items():
  s=C[k];cn=f' and {c}-word count' if c else '';r={x:'' for x in F};r.update(tlg_author_id=k[0],tlg_work_id=k[1],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested=f'Exact local Canon, First1KGreek, Perseus, OPP, PTA and scan registry checked item by item; {l}{cn} verified.',open_text_result=f'No exact licensed TEI matching {l} was verified.',confidence='high',notes=n+' No image or OCR used.',last_checked='2026-08-11')
  if k==('4538','001'):r.update(scan_result='Exact-edition page-image candidate identified but not yet visually sampled.',scan_url='https://play.google.com/store/books/details?id=gh1V9iRHqvEC',scan_rights='Free Google Books ebook; provider terms/private-use route to be recorded before transfer.',proposed_status='CANDIDATE_SCAN_EXACT_EDITION_UNSAMPLED',next_action='Resolve exact page-image endpoints and visually confirm Greek on p.1 and p.14 before any transfer to the selected binary store.')
  else:r.update(scan_result=f'No reusable page-image source matching {l} is registered locally.',proposed_status='NO_EXACT_OPEN_TEXT',next_action=f'Locate page images for {l}; visually confirm Greek before private-repository transfer; do not use provider OCR.')
  w.writerow(r)
