import csv
FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split()
def build(output,works):
 canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
 with open(output,'w',newline='',encoding='utf-8') as h:
  w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
  for work in works:
   s=canon[('0085',work)];row={f:'' for f in FIELDS};row.update(tlg_author_id='0085',tlg_work_id=work,author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local First1K and Perseus Aeschylus TEIs; modern fragment and duplicate-edition boundaries checked.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
   c=[r for r in matches if r['tlg_author_id']=='0085' and r['tlg_work_id']==work and r['corpus']=='First1KGreek'];v=[r for r in checks if r['tlg_author_id']=='0085' and r['tlg_work_id']==work and r['corpus']=='First1KGreek']
   if int(work)<=7 and len(c)==len(v)==1 and v[0]['automated_check']=='AUTOMATED_TEI_CHECK_PASSED': row.update(open_text_result='Complete licensed Greek tragedy verified in a historical open edition; it is an alternative to the Murray edition cited by the Canon.',open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_ALTERNATE_EDITION',next_action='Prepare licensed TEI with its exact source-edition provenance.',notes=f"Exact work URN {c[0]['cts_urn']}; {v[0]['greek_characters']} Greek characters; [Sp.] status retained where applicable; no OCR/images used.")
   elif work in {'012','013','014','015','016','017','018'}: row.update(open_text_result='This Page 1972 item duplicates a tragedy already represented by an open historical text, but Page readings are not claimed as covered.',confidence='high',proposed_status='DUPLICATE_WORK_OPEN_ALTERNATE_EDITION',next_action='Link to the corresponding open tragedy without copying Page 1972.',notes='Work-level coverage distinguished from exact-edition coverage; no OCR/images used.')
   elif work=='010': row.update(open_text_result='AG 7.255 and 10.110 are concrete open-text leads, but attribution-level concordance remains required.',confidence='medium',proposed_status='PARTIAL_OPEN_TEXT_REQUIRES_AG_CONCORDANCE',next_action='Verify both AG loci individually.',notes='No aggregate fragment completeness inferred.')
   else: row.update(open_text_result='No complete licensed Greek transcription matching this exact modern fragment aggregate was verified.',confidence='medium',proposed_status='NO_COMPLETE_OPEN_TEXT',next_action='Map fragments to individual ancient or papyrus witnesses.',notes='Complete tragedies and neighbouring fragment editions are not substituted; no OCR/images used.')
   w.writerow(row)
