import csv
START=('0751','004');OUTPUT='data/research_batches/detailed_verified_3001_batch_237.csv';F='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();c=list(csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8')));v=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')));i=next(i for i,r in enumerate(c)if(r['tlg_author_id'],r['tlg_work_id'])==START)
with open(OUTPUT,'w',newline='',encoding='utf-8')as h:
 w=csv.DictWriter(h,fieldnames=F);w.writeheader()
 for s in c[i:i+5]:
  x=next((x for x in v if(x['tlg_author_id'],x['tlg_work_id'])==(s['tlg_author_id'],s['tlg_work_id'])and x['automated_check']=='AUTOMATED_TEI_CHECK_PASSED'),None);r={f:''for f in F};r.update(tlg_author_id=s['tlg_author_id'],tlg_work_id=s['tlg_work_id'],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],last_checked='2026-08-11')
  if s['record_type']=='cross_reference':r.update(sources_tested='Canonical notice and its named TLG cross-reference checked.',open_text_result='No independent work record: follow the cited TLG work.',scan_result='No separate edition or page-image object applies to this cross-reference.',confidence='high',proposed_status='CROSS_REFERENCE',next_action='Research the cited TLG work; retain this cross-reference record.',notes='No image acquired; no OCR used.')
  elif x:r.update(sources_tested='Exact TLG identifier matched against locally verified TEI metadata.',open_text_result='Exact licensed TEI match verified locally.',open_text_url=x['text_url'],open_text_license=x['tei_license'],scan_result='No edition-matching reusable page-image source verified.',confidence='high',proposed_status='TEXT_VERIFIED',next_action='Use the verified TEI; assess edition variance before publication.',notes='No image acquired; no OCR used.')
  else:r.update(sources_tested='Exact TLG/First1K lookup; cited critical-edition bibliographic record checked.',open_text_result='No exact licensed TEI match in local corpus.',scan_result='No edition-matching reusable page-image source verified.',confidence='medium',proposed_status='EDITION_IDENTIFIED',next_action='Locate a rights-cleared scan of the cited edition; do not substitute OCR.',notes='No image acquired.')
  w.writerow(r)
