import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_634.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();WORKS=['002','003','004','005','006'];canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for work in WORKS:
  s=canon[('0096',work)];c=[r for r in matches if r['tlg_author_id']=='0096' and r['tlg_work_id']==work];v=[r for r in checks if r['tlg_author_id']=='0096' and r['tlg_work_id']==work and r['automated_check']=='AUTOMATED_TEI_CHECK_PASSED'];row={f:'' for f in FIELDS};row.update(tlg_author_id='0096',tlg_work_id=work,author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon Aesop item; local First1K fable TEIs and collection boundaries checked.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
  if work=='002' and c and v: row.update(open_text_result='Large complete licensed Greek Aesop fable collection verified in an open historical edition; exact Hausrath–Hunger identity is not asserted.',open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_ALTERNATE_EDITION',next_action='Prepare licensed collection with exact source provenance.',notes=f"{v[0]['greek_characters']} Greek characters; collection boundaries retained; no OCR/images used.")
  else: row.update(open_text_result='No exact licensed Greek transcription of this separately edited fable subset was verified.',confidence='medium',proposed_status='NO_EXACT_OPEN_TEXT',next_action='Map the subset against the open collection or its direct witness before promotion.',notes='No inclusion in 0096.002 inferred merely from adjacent bibliography; no OCR/images used.')
  w.writerow(row)
