import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_624.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();TARGETS=[('0068','001'),('0068','002'),('0071','001'),('0071','002'),('0075','001')]
canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for key in TARGETS:
  s=canon[key];row={f:'' for f in FIELDS};row.update(tlg_author_id=key[0],tlg_work_id=key[1],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local First1K Müller Greek TEI; modern duplicate/partial-duplicate edition boundaries checked.',scan_result='No scan acquisition needed for open Müller texts; no other scan promoted.',last_checked='2026-08-11')
  c=[r for r in matches if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['corpus']=='First1KGreek'];v=[r for r in checks if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['corpus']=='First1KGreek']
  if key in {('0068','001'),('0071','001'),('0075','001')} and len(c)==len(v)==1 and v[0]['automated_check']=='AUTOMATED_TEI_CHECK_PASSED': row.update(open_text_result='Complete licensed Greek TEI verified in the exact K. Müller 1855 edition cited by the Canon.',open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_EXACT_EDITION',next_action='Prepare exact licensed TEI for ingestion.',notes=f"Exact URN {c[0]['cts_urn']}; {v[0]['greek_characters']} Greek characters; no OCR/images used.")
  elif key==('0068','002'): row.update(open_text_result='Diller 1952 vv.722–1026 partly duplicates the open Müller text 0068.001, but its additional vv.981–1026 and readings are not claimed as covered.',confidence='high',proposed_status='PARTIAL_DUPLICATE_OF_0068.001',next_action='Map and source only the non-overlapping Diller verses.',notes='No modern copyrighted text copied and no overlap promoted as complete.')
  else: row.update(open_text_result='Casson 1989 is a distinct modern edition duplicating the work of open Müller host 0071.001; no separate text copied.',confidence='high',proposed_status='DUPLICATE_WORK_ALTERNATE_EDITION_0071.001',next_action='Use open Müller host for work coverage while retaining Casson bibliography.',notes='Edition-level distinction preserved; no OCR/images used.')
  w.writerow(row)
