import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_613.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();TARGETS=[('0053','001'),('0055','001'),('0056','001'),('0058','001'),('0059','001')]
canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for key in TARGETS:
  s=canon[key]; candidates=[r for r in matches if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1]]; verified=[r for r in checks if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['automated_check']=='AUTOMATED_TEI_CHECK_PASSED'];row={f:'' for f in FIELDS};row.update(tlg_author_id=key[0],tlg_work_id=key[1],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local First1K/Perseus registry, source-edition metadata and Greek verification.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
  if candidates and verified:
   c=candidates[0];v=verified[0]; exact=key[0] in {'0053','0055'}; row.update(open_text_result=('Complete Greek TEI verified in the exact edition cited by the Canon.' if exact else 'Complete licensed Greek text verified in an open historical alternative edition.'),open_text_url=c['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_EXACT_EDITION' if exact else 'OPEN_TEXT_COMPLETE_ALTERNATE_EDITION',next_action='Prepare licensed TEI while retaining edition provenance.',notes=f"Exact work URN {c['cts_urn']}; {v['greek_characters']} Greek characters; automated check passed. Plato TEI metadata says Burnet 1905 while Canon says vol. 1 (1900), so exact-edition identity is not asserted. No OCR/images used.")
  else: row.update(open_text_result='No exact licensed Greek transcription was verified.',confidence='medium',proposed_status='NO_EXACT_OPEN_TEXT',next_action='Locate the exact Hercher item or primary witness.',notes='No neighbouring item substituted; no OCR/images used.')
  w.writerow(row)
