import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_629.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();TARGETS=[('0089','001'),('0090','001'),('0091','001'),('0093','001'),('0093','002')]
canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for key in TARGETS:
  s=canon[key];row={f:'' for f in FIELDS};row.update(tlg_author_id=key[0],tlg_work_id=key[1],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local First1K/Perseus Greek TEIs and AG registry; edition boundaries checked.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
  c=[r for r in matches if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['corpus'] in {'First1KGreek','Perseus'}];v=[r for r in checks if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['automated_check']=='AUTOMATED_TEI_CHECK_PASSED']
  if key==('0090','001') and c and v: row.update(open_text_result='Complete Greek text verified in the exact Müller 1861 edition cited by the Canon.',open_text_url=[x for x in c if x['corpus']=='Perseus'][0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_EXACT_EDITION',next_action='Prepare exact licensed TEI.',notes='Multiple OPP encodings exist; the Müller edition identity is explicit. No OCR/images used.')
  elif key[0]=='0093' and c and v: row.update(open_text_result='Complete licensed Greek text verified in an open historical edition; exact identity with the Canon edition is not asserted.',open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_ALTERNATE_EDITION',next_action='Preserve source edition and, for De causis plantarum, restrict Canon mapping to book 1.',notes=f"Exact work URN {c[0]['cts_urn']}; {v[0]['greek_characters']} Greek characters; no OCR/images used.")
  elif key==('0091','001'): row.update(open_text_result='AG 7.291 and 16.186 are concrete open-text leads requiring attribution-level concordance.',confidence='medium',proposed_status='PARTIAL_OPEN_TEXT_REQUIRES_AG_CONCORDANCE',next_action='Verify both AG loci individually.',notes='No aggregate completeness inferred.')
  else: row.update(open_text_result='No complete licensed Greek transcription matching Wehrli 1969 fragment aggregate was verified.',confidence='medium',proposed_status='NO_COMPLETE_OPEN_TEXT',next_action='Map fragments to individual ancient witnesses.',notes='No neighbouring philosophical corpus substituted; no OCR/images used.')
  w.writerow(row)
