import csv
FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split()
def build(output,works):
 canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
 with open(output,'w',newline='',encoding='utf-8') as h:
  w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
  for work in works:
   s=canon[('0059',work)];c=[r for r in matches if r['tlg_author_id']=='0059' and r['tlg_work_id']==work and r['corpus']=='Perseus'];v=[r for r in checks if r['tlg_author_id']=='0059' and r['tlg_work_id']==work and r['corpus']=='Perseus'];assert len(c)==len(v)==1 and v[0]['automated_check']=='AUTOMATED_TEI_CHECK_PASSED';row={f:'' for f in FIELDS}
   row.update(tlg_author_id='0059',tlg_work_id=work,author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local Perseus Burnet Greek TEI, CTS work identity, repository CC BY-SA 4.0 and automated Greek-content check.',open_text_result='Complete licensed Greek Burnet text verified. It is conservatively classed as an alternative because the Perseus volume/year metadata does not always exactly reproduce the Canon bibliography.',open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0 (Perseus repository)',scan_result='No scan acquisition needed because a complete licensed Greek TEI exists.',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_ALTERNATE_EDITION',next_action='Prepare licensed TEI while preserving the precise Perseus Burnet volume metadata.',notes=f"Exact CTS URN {c[0]['cts_urn']}; {v[0]['greek_characters']} Greek characters; automated check passed. Spurious/dubious flags from Canon retained; no OCR/images used.",last_checked='2026-08-11');w.writerow(row)
