import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_632.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();WORKS=['013','014','015','016','017'];canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))}
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for work in WORKS:
  s=canon[('0093',work)];row={f:'' for f in FIELDS};row.update(tlg_author_id='0093',tlg_work_id=work,author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local Theophrastus TEIs and item/duplicate boundaries checked.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
  if work=='014': row.update(open_text_result='The open De causis plantarum TEI at 0093.002 contains books 2–6 as an alternative historical edition; the Wimmer mapping remains distinct.',open_text_url='https://scaife.perseus.org/reader/urn:cts:greekLit:tlg0093.tlg002.1st1K-grc1:2.1.1',open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_ALTERNATE_EDITION_HOST_0093.002',next_action='Map books 2–6 from the open host without duplicating the TEI.',notes='Canonical book split preserved; no OCR/images used.')
  elif work=='016': row.update(open_text_result='This short Wimmer passage is represented at work level in open Historia plantarum 0093.001, but Wimmer readings are not claimed.',confidence='high',proposed_status='OPEN_TEXT_ALTERNATE_EDITION_HOST_0093.001',next_action='Map 9.18.3–11 in the open host.',notes='No exact-edition equivalence asserted.')
  elif work=='017': row.update(open_text_result='Amigues 2003–2006 duplicates the work of open Historia plantarum host 0093.001; no modern text copied.',confidence='high',proposed_status='DUPLICATE_WORK_OPEN_ALTERNATE_EDITION_0093.001',next_action='Use open host for work coverage and retain Amigues bibliography.',notes='Edition-level distinction preserved.')
  else: row.update(open_text_result='No complete licensed Greek transcription matching this exact papyrus or fragment edition was verified.',confidence='medium',proposed_status='NO_COMPLETE_OPEN_TEXT',next_action='Locate and visually verify the primary papyrus/manuscript witness.',notes='No neighbouring Theophrastus work substituted; no OCR/images used.')
  w.writerow(row)
