import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_622.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();TARGETS=[('0059','042'),('0064','001'),('0065','001'),('0065','002'),('0065','003')]
canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for key in TARGETS:
  s=canon[key];row={f:'' for f in FIELDS};row.update(tlg_author_id=key[0],tlg_work_id=key[1],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local open TEI registries; duplicate and FGrH boundaries checked.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
  c=[r for r in matches if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['corpus']=='First1KGreek'];v=[r for r in checks if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['corpus']=='First1KGreek']
  if key in {('0064','001'),('0065','001')} and len(c)==len(v)==1 and v[0]['automated_check']=='AUTOMATED_TEI_CHECK_PASSED': row.update(open_text_result='Complete Greek TEI verified in the exact K. Müller 1855 edition cited by the Canon.',open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_EXACT_EDITION',next_action='Prepare exact licensed TEI for ingestion.',notes=f"Exact URN {c[0]['cts_urn']}; {v[0]['greek_characters']} Greek characters; file licence verified; no OCR/images used.")
  elif key==('0059','042'): row.update(open_text_result='This Slings 2003 Republic notice is bibliographically distinct from Plato 0059.030; the open Burnet Republic is only an alternate edition and is not duplicated here.',confidence='high',proposed_status='ALTERNATE_EDITION_HOST_0059.030',next_action='Retain one open Burnet text under 0059.030 and this modern-edition relation without duplication.',notes='No Slings text copied; duplicate work identity does not imply exact-edition coverage.')
  else: row.update(open_text_result='No complete licensed Greek transcription matching this exact FGrH testimony/fragment aggregate was verified.',confidence='medium',proposed_status='NO_COMPLETE_OPEN_TEXT',next_action='Map FGrH entries to individual ancient witnesses.',notes='The complete Periplus is not extended to separate testimonia or fragments; no OCR/images used.')
  w.writerow(row)
