import csv

START=("3103","002"); OUTPUT="data/research_batches/detailed_verified_3001_batch_265.csv"
FIELDS="tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked".split()
DETAILS={
("3103","002"):dict(sources_tested="Exact local TLG, First1KGreek, Perseus and PTA identifier-path lookup; Gigante 1979 pp. 73–84 item checked; local scan register checked.",open_text_result="No exact licensed TEI of Nicolaus Hydruntinus' Carmina in Gigante 1979 was found.",scan_result="No reusable images of Gigante 1979 pp. 73–84 are registered locally.",confidence="high",proposed_status="NO_EXACT_OPEN_TEXT",next_action="Locate rights-cleared images of pp. 73–84 and establish poem-by-poem boundaries before transcription or OCR.",notes="No image acquisition or OCR used."),
("3103","003"):dict(sources_tested="Exact local TLG, First1KGreek, Perseus and PTA identifier-path lookup; Chronz 2009 pp. 1–271 edition requirement checked; local scan register checked.",open_text_result="No exact licensed TEI of the 2009 Chronz edition was found.",scan_result="No reusable page-image source for Chronz 2009 pp. 1–271 is registered locally.",confidence="high",proposed_status="NO_EXACT_OPEN_TEXT",next_action="Seek an authorized digital text or rights-cleared scan of Chronz 2009; verify the full edition before transcription or OCR.",notes="No alternate anti-Jewish disputation was substituted; no image or OCR used."),
("0933","x01"):dict(sources_tested="Canon item, five exact Kühn loci K12.488, K12.788, K13.353, K13.512 and K13.747, and explicit hosts 0057.076/077 inspected; local host paths and scan register checked.",open_text_result="No independent Hygienus holding applies: the five fragments must remain locus links within Galen hosts 0057.076 and 0057.077.",scan_result="No separate scan object applies to this cross-reference.",confidence="high",proposed_status="CROSS_REFERENCE_HOSTS_0057.076_0057.077",next_action="Map each of the five Kühn loci to the correct one of hosts 0057.076/077 and record item-level text and image provenance there.",notes="Five explicit loci and both hosts preserved without inferring their individual host allocation; no image or OCR used."),
("0742","001"):dict(sources_tested="Exact local TLG, First1KGreek, Perseus and PTA identifier-path lookup; Heitsch 1963 2nd edn. pp. 155–157 item checked; local scan register checked.",open_text_result="No exact licensed TEI of the Naassene poems in the specified Heitsch edition was found.",scan_result="No reusable images of Heitsch 1963 pp. 155–157 are registered locally.",confidence="high",proposed_status="NO_EXACT_OPEN_TEXT",next_action="Locate rights-cleared images of pp. 155–157 and verify every fragment boundary before transcription or OCR.",notes="No image acquisition or OCR used."),
("0742","002"):dict(sources_tested="Exact local TLG, First1KGreek, Perseus and PTA identifier-path lookup; Heitsch 1963 2nd edn. pp. 157–164 item checked; local scan register checked.",open_text_result="No exact licensed TEI of the Christian poems in the specified Heitsch edition was found.",scan_result="No reusable images of Heitsch 1963 pp. 157–164 are registered locally.",confidence="high",proposed_status="NO_EXACT_OPEN_TEXT",next_action="Locate rights-cleared images of pp. 157–164 and verify the Christian-carmina item boundary before transcription or OCR.",notes="The shared p. 157 boundary with 0742.001 requires visual item separation; no image or OCR used.")}
coverage=list(csv.DictReader(open("data/canon_coverage.csv",encoding="utf-8"))); i=next(i for i,r in enumerate(coverage) if (r["tlg_author_id"],r["tlg_work_id"])==START); items=coverage[i:i+5]
assert [(r["tlg_author_id"],r["tlg_work_id"]) for r in items]==list(DETAILS)
with open(OUTPUT,"w",newline="",encoding="utf-8") as h:
 w=csv.DictWriter(h,fieldnames=FIELDS); w.writeheader()
 for s in items:
  k=(s["tlg_author_id"],s["tlg_work_id"]); r={f:"" for f in FIELDS}; r.update(tlg_author_id=k[0],tlg_work_id=k[1],author_heading=s["author_heading"],work_title=s["work_title"],canonical_edition=s["bibliographic_notice"],last_checked="2026-08-11"); r.update(DETAILS[k]); w.writerow(r)
