import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_612.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();TARGETS=[('0046','001'),('0047','001'),('0048','001'),('0049','001'),('0050','001')]
canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for key in TARGETS:
  s=canon[key];c=[r for r in matches if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['corpus']=='First1KGreek'];v=[r for r in checks if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['corpus']=='First1KGreek'];row={f:'' for f in FIELDS};row.update(tlg_author_id=key[0],tlg_work_id=key[1],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local First1K Hercher corpus and Greek verification; strict item boundary.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
  if len(c)==len(v)==1 and v[0]['automated_check']=='AUTOMATED_TEI_CHECK_PASSED': row.update(open_text_result='Complete Greek TEI verified in the exact Hercher 1873 edition cited by the Canon.',open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_EXACT_EDITION',next_action='Prepare exact licensed TEI for ingestion.',notes=f"Exact URN {c[0]['cts_urn']}; explicit licence; {v[0]['greek_characters']} Greek characters; no OCR/images used.")
  else: row.update(open_text_result='No exact licensed Greek transcription of this Hercher letter was verified in the local open corpora.',confidence='medium',proposed_status='NO_EXACT_OPEN_TEXT',next_action='Locate the exact Hercher item or its primary witness.',notes='No neighbouring epistolary item substituted; no OCR/images used.')
  w.writerow(row)
