import csv

START=("2052","002"); OUTPUT="data/research_batches/detailed_verified_3001_batch_264.csv"
FIELDS="tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked".split()
DETAILS={
("2052","002"):dict(sources_tested="Exact local TLG, First1KGreek, Perseus and PTA identifier-path lookup; FGrH 630, 3C:180 testimony locus checked; local scan register checked.",open_text_result="No exact licensed TEI of the Horapollo testimonia at FGrH 630, 3C:180 was found.",scan_result="No reusable page image of the exact FGrH testimony locus is registered locally.",confidence="high",proposed_status="NO_EXACT_OPEN_TEXT",next_action="Locate the exact FGrH 630 testimony page in a rights-cleared scan and transcribe only the stated item after visual verification.",notes="Testimonia are a distinct item from 2052.001; no image or OCR used."),
("5359","001"):dict(sources_tested="Exact local TLG, First1KGreek, Perseus and PTA identifier-path lookup; Ajjoub–Paramelle 2004 pp. 172–454 even-page Greek item checked; local scan register checked.",open_text_result="No exact licensed TEI of the Sinaiticus gr. 864 Horologium in the 2004 Sources chrétiennes edition was found.",scan_result="No reusable images of the required even pages 172–454 are registered locally.",confidence="high",proposed_status="NO_EXACT_OPEN_TEXT",next_action="Obtain rights clearance for the 2004 edition or locate an authorized digital text, preserving the even-page Greek-text boundary.",notes="The odd facing pages must not be silently treated as the canonical Greek item; no image or OCR used."),
("4487","001"):dict(sources_tested="Exact local TLG, First1KGreek, Perseus and PTA identifier-path lookup; Thomson 1960 pp. 25–95 odd-page Greek item checked; local scan register checked.",open_text_result="No exact licensed TEI of Thomson's Clarkianus XI text was found.",scan_result="No reusable images of the required odd pages 25–95 are registered locally.",confidence="high",proposed_status="NO_EXACT_OPEN_TEXT",next_action="Locate a rights-cleared copy of Thomson 1960 and capture only the visually verified Greek text on odd pages 25–95.",notes="The trailing HYBRIAS/HYBRISTUS headings in the extracted notice are not part of Hortus symbolicus; no image or OCR used."),
("0932","x01"):dict(sources_tested="Canon item, exact Kühn locus K14.188, and explicit host reference 0057.078 inspected; local host identifier paths and scan register checked.",open_text_result="No independent Hybristus holding applies: the fragment is a locus within canonical Galen host 0057.078.",scan_result="No separate scan object applies to this cross-reference.",confidence="high",proposed_status="CROSS_REFERENCE_HOST_0057.078",next_action="Verify K14.188 within 0057.078 and attach locus-level text, edition, rights, and image provenance to that host.",notes="Cross-reference and exact single locus preserved; no separate acquisition, image, or OCR used."),
("3103","001"):dict(sources_tested="Exact local TLG, First1KGreek, Perseus and PTA identifier-path lookup; Hoeck–Loenertz 1965 pp. 130–135 and Epistula 1 boundary checked; local scan register checked.",open_text_result="No exact licensed TEI of Epistula 1 in Hoeck–Loenertz 1965 was found.",scan_result="No reusable images of pp. 130–135 are registered locally.",confidence="high",proposed_status="NO_EXACT_OPEN_TEXT",next_action="Locate rights-cleared images of pp. 130–135 and verify the Epistula 1 incipit/addressee before transcription or OCR.",notes="The item is Epistula 1, not an inferred range of letters; no image or OCR used.")}
coverage=list(csv.DictReader(open("data/canon_coverage.csv",encoding="utf-8"))); i=next(i for i,r in enumerate(coverage) if (r["tlg_author_id"],r["tlg_work_id"])==START); items=coverage[i:i+5]
assert [(r["tlg_author_id"],r["tlg_work_id"]) for r in items]==list(DETAILS)
with open(OUTPUT,"w",newline="",encoding="utf-8") as h:
 w=csv.DictWriter(h,fieldnames=FIELDS); w.writeheader()
 for s in items:
  k=(s["tlg_author_id"],s["tlg_work_id"]); r={f:"" for f in FIELDS}; r.update(tlg_author_id=k[0],tlg_work_id=k[1],author_heading=s["author_heading"],work_title=s["work_title"],canonical_edition=s["bibliographic_notice"],last_checked="2026-08-11"); r.update(DETAILS[k]); w.writerow(r)
