import csv
OUTPUT='data/research_batches/detailed_verified_3001_batch_633.csv';FIELDS='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split();TARGETS=[('0093','018'),('0094','001'),('0094','002'),('0094','003'),('0096','001')];canon={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))};matches=list(csv.DictReader(open('data/corpus_matches.csv',encoding='utf-8')));checks=list(csv.DictReader(open('data/text_verification.csv',encoding='utf-8')))
with open(OUTPUT,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=FIELDS,lineterminator='\n');w.writeheader()
 for key in TARGETS:
  s=canon[key];c=[r for r in matches if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1]];v=[r for r in checks if r['tlg_author_id']==key[0] and r['tlg_work_id']==key[1] and r['automated_check']=='AUTOMATED_TEI_CHECK_PASSED'];row={f:'' for f in FIELDS};row.update(tlg_author_id=key[0],tlg_work_id=key[1],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested='Exact Canon notice; local licensed TEI registries and edition boundaries.',scan_result='No separate scan promoted.',last_checked='2026-08-11')
  if key[0]=='0094' and c and v: row.update(open_text_result=('Complete Greek text verified in the exact Müller edition.' if key[1]=='001' else 'Complete Greek text verified in a licensed historical alternative edition.'),open_text_url=c[0]['text_url'],open_text_license='CC BY-SA 4.0',confidence='high',proposed_status='OPEN_TEXT_COMPLETE_EXACT_EDITION' if key[1]=='001' else 'OPEN_TEXT_COMPLETE_ALTERNATE_EDITION',next_action='Prepare licensed TEI with edition provenance.',notes=f"{v[0]['greek_characters']} Greek characters; automated check passed; no OCR/images used.")
  else: row.update(open_text_result='No exact complete licensed Greek transcription of this vernacular translation or proverb selection was verified.',confidence='medium',proposed_status='NO_EXACT_OPEN_TEXT',next_action='Locate the exact edition or primary witness.',notes='Characteres Greek source and neighbouring Aesop fables are not substituted; no OCR/images used.')
  w.writerow(row)
