import csv
O='data/research_batches/detailed_verified_3001_batch_548.csv';F='tlg_author_id tlg_work_id author_heading work_title canonical_edition sources_tested open_text_result open_text_url open_text_license scan_result scan_url scan_rights confidence proposed_status next_action notes last_checked'.split()
D={('4538','007'):('Treu 1899 pp.37–38','','Exact-volume Google Books/HathiTrust candidate shared with 4538.001–006.'),('4539','001'):('Oehler 1957 pp.32–33','','No count absent from the Canon is invented.'),('4540','001'):('MPG 154 cols.729–745','','The [Dub.] status, possible Philotheus Coccinus attribution, CPG 7865 and cross-reference are preserved.'),('4541','001'):('Paschou 1982 pp.282–294; Pan.Chalc.[51]53','','BHG 129j and the exact witness are preserved.'),('5007','001'):('Ludwich 1896 pp.198–308','30,080','The scholia and paraphrase volume is not conflated with the base poem.')}
C={(r['tlg_author_id'],r['tlg_work_id']):r for r in csv.DictReader(open('data/canon_coverage.csv',encoding='utf-8'))}
with open(O,'w',newline='',encoding='utf-8') as h:
 w=csv.DictWriter(h,fieldnames=F,lineterminator='\n');w.writeheader()
 for k,(l,c,n) in D.items():
  s=C[k];cn=f' and {c}-word count' if c else '';r={x:'' for x in F};r.update(tlg_author_id=k[0],tlg_work_id=k[1],author_heading=s['author_heading'],work_title=s['work_title'],canonical_edition=s['bibliographic_notice'],sources_tested=f'Exact local Canon, First1KGreek, Perseus, OPP, PTA and scan registry checked item by item; {l}{cn} verified.',open_text_result=f'No exact licensed TEI matching {l} was verified.',confidence='high',notes=n+' No image or OCR used.',last_checked='2026-08-11')
  if k==('4538','007'):r.update(scan_result='Exact-edition page-image candidate identified but not yet Greek-sampled.',scan_url='https://play.google.com/store/books/details?id=gh1V9iRHqvEC',scan_rights='Free Google Books ebook; provider terms/private-use route to record.',proposed_status='CANDIDATE_SCAN_EXACT_EDITION_UNSAMPLED',next_action='Resolve p.37–38 page images and visually confirm Greek before transfer to the selected binary store.')
  else:r.update(scan_result=f'No reusable page-image source matching {l} is registered locally.',proposed_status='NO_EXACT_OPEN_TEXT',next_action=f'Locate page images for {l}; visually confirm Greek before transfer; do not use provider OCR.')
  w.writerow(r)
